server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: /
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}

spring:
  application:
    name: report-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:reportdb}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

azure:
  storage:
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING}
    container:
      reports: ${AZURE_CONTAINER_REPORTS:reports}

file:
  storage:
    location: ${FILE_STORAGE_LOCATION:./reports}
    expiry-time-minutes: ${FILE_EXPIRY_TIME:30}

token:
  cleanup-cron: ${TOKEN_CLEANUP_CRON:0 0 * * * *}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /api-docs

logging:
  level:
    com.ktds.bidw.report: ${LOG_LEVEL:DEBUG}

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true